test

diff --git a/.github/workflows/acceptance.yml b/.github/workflows/acceptance.yml
--- a/.github/workflows/acceptance.yml
+++ b/.github/workflows/acceptance.yml
@@ -56,13 +56,20 @@ jobs:
           HOSTNAME_TO_FIND="mysql"
 
           # Find container ID by hostname
-          for container_id in $(docker ps -q); do \
-            if [ "$(docker inspect -f '{{.Config.Hostname}}' $container_id)" = "$HOSTNAME_TO_FIND" ]; then \
-              ID=$container_id; \
-            fi; \
+          for container_id in $(docker ps -q); do
+            echo "Checking container ID: $container_id";
+            if [ "$(docker inspect -f '{{.Config.Hostname}}' $container_id)" = "$HOSTNAME_TO_FIND" ]; then
+              ID=$container_id
+              break
+            fi
           done
 
-          docker inspect $ID --format '{{json .NetworkSettings.Networks}}'
+          if [ "$ID" = "" ]; then
+            echo "Could not find MySQL / MariaDB container by hostname: $HOSTNAME_TO_FIND"
+            exit 1
+          fi
+
+          docker inspect "$ID" --format '{{json .NetworkSettings.Networks}}'
           MYSQL_NETWORK=$(docker inspect $ID --format '{{json .NetworkSettings.Networks}}' | \
             php -r 'echo json_encode(array_key_first(json_decode(file_get_contents("php://stdin"), associative: true, flags: JSON_THROW_ON_ERROR)));')
 
